# Generated by Django 5.2 on 2026-08-15 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_codefconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_closes', to='businesses.business')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('business', 'year', 'month'), name='uniq_business_monthly_close')],
            },
        ),
    ]
