# Generated by Django 5.2 on 2026-08-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_number', models.CharField(blank=True, max_length=20, null=True)),
                ('industry_code', models.CharField(blank=True, max_length=20)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('business_item', models.CharField(blank=True, max_length=100)),
                ('business_status', models.CharField(default='UNKNOWN', max_length=20)),
                ('tax_type', models.CharField(default='UNKNOWN', max_length=20)),
                ('tax_type_code', models.CharField(blank=True, max_length=10)),
                ('tax_type_changed_date', models.DateField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
