# Generated by Django 5.2 on 2026-08-14 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_taxtypehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodefConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('CARD', 'CARD'), ('HOMETAX', 'HOMETAX')], max_length=20)),
                ('status', models.CharField(choices=[('DISCONNECTED', 'DISCONNECTED'), ('AUTH_REQUIRED', 'AUTH_REQUIRED'), ('CONNECTED', 'CONNECTED'), ('FAILED', 'FAILED')], default='DISCONNECTED', max_length=20)),
                ('connected_id', models.CharField(blank=True, max_length=255)),
                ('continue_2way', models.BooleanField(default=False)),
                ('method', models.CharField(blank=True, max_length=50)),
                ('job_index', models.IntegerField(blank=True, null=True)),
                ('thread_index', models.IntegerField(blank=True, null=True)),
                ('jti', models.CharField(blank=True, max_length=255)),
                ('two_way_timestamp', models.BigIntegerField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=50)),
                ('last_error_message', models.TextField(blank=True)),
                ('last_raw_response', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codef_connections', to='businesses.business')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('business', 'connection_type'), name='uniq_business_codef_connection')],
            },
        ),
    ]
