# Generated by Django 5.2 on 2026-08-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_codefconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='representative_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
