# Generated by Django 5.2 on 2026-08-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_business_representative_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tax_accountant_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
