# Generated by Django 5.2 on 2026-08-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_tax_accountant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefconnection',
            name='pending_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codefconnection',
            name='pending_operation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='codefconnection',
            name='pending_source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='codefconnection',
            name='pending_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]