# Generated by Django 5.2 on 2026-08-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_codefconnection_pending_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='birth_date',
            field=models.CharField(blank=True, default='1988-05-12', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='phone_number',
            field=models.CharField(blank=True, default='010-1234-5678', max_length=30),
        ),
    ]
