# Generated by Django 5.2 on 2026-08-15 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_codefconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('PRO', '카페비서 Pro')], default='PRO', max_length=20)),
                ('price', models.PositiveIntegerField(default=19900)),
                ('status', models.CharField(choices=[('ACTIVE', '구독 이용 중'), ('CANCELLED', '구독 취소됨')], default='ACTIVE', max_length=20)),
                ('next_billing_date', models.DateField()),
                ('cancelled_at', models.DateField(blank=True, null=True)),
                ('access_until', models.DateField(blank=True, null=True)),
                ('billing_key_encrypted', models.CharField(blank=True, max_length=255)),
                ('card_company', models.CharField(blank=True, max_length=50)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='businesses.business')),
            ],
        ),
    ]
