# Generated by Django 5.2 on 2026-08-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_businessprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessProfile',
        ),
    ]
