# Generated by Django 5.2 on 2026-08-16 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0005_business_tax_accountant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('generated', '생성됨'), ('approved', '승인됨')], default='generated', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='reports/csv/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdf/')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='businesses.business')),
            ],
            options={
                'unique_together': {('business', 'year_month')},
            },
        ),
    ]
