# Generated by Django 5.2 on 2026-08-16

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("businesses", "0003_codefconnection"),
        ("transactions", "0002_transaction_deduction_and_sales_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeductionReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("suggested_status", models.CharField(choices=[("DEDUCTIBLE_CANDIDATE", "공제 후보"), ("NON_DEDUCTIBLE_CANDIDATE", "불공제 후보"), ("REVIEW_REQUIRED", "검토 필요")], default="REVIEW_REQUIRED", max_length=40)),
                ("suggestion_source", models.CharField(choices=[("CODEF", "CODEF"), ("RULE", "규칙"), ("AI", "AI")], default="RULE", max_length=20)),
                ("suggestion_reason", models.TextField(blank=True)),
                ("confidence", models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ("confirmed_status", models.CharField(choices=[("UNCONFIRMED", "미확정"), ("DEDUCTIBLE", "공제"), ("NON_DEDUCTIBLE", "불공제")], default="UNCONFIRMED", max_length=20)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="deduction_review", to="transactions.transaction")),
            ],
            options={"ordering": ["-transaction__transaction_date", "-id"]},
        ),
        migrations.CreateModel(
            name="MonthlyClose",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("status", models.CharField(choices=[("OPEN", "진행 중"), ("CLOSED", "마감")], default="OPEN", max_length=10)),
                ("sales_amount", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("purchase_amount", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("output_vat", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("deductible_input_vat", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("estimated_vat", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="monthly_closes", to="businesses.business")),
            ],
            options={"ordering": ["-year", "-month"]},
        ),
        migrations.AddIndex(model_name="deductionreview", index=models.Index(fields=["confirmed_status"], name="deduction_confirmed_idx")),
        migrations.AddIndex(model_name="deductionreview", index=models.Index(fields=["suggested_status"], name="deduction_suggested_idx")),
        migrations.AddConstraint(
            model_name="deductionreview",
            constraint=models.CheckConstraint(
                condition=Q(("confidence__isnull", True))
                | Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="deduction_confidence_range",
            ),
        ),
        migrations.AddIndex(model_name="monthlyclose", index=models.Index(fields=["business", "status", "year", "month"], name="close_biz_status_period_idx")),
        migrations.AddConstraint(model_name="monthlyclose", constraint=models.UniqueConstraint(fields=("business", "year", "month"), name="uniq_business_monthly_close")),
        migrations.AddConstraint(
            model_name="monthlyclose",
            constraint=models.CheckConstraint(
                condition=Q(("month__gte", 1), ("month__lte", 12)),
                name="monthly_close_month_range",
            ),
        ),
    ]
