"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
from cryptography.fernet import Fernet

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

IS_TEST_RUN = "test" in sys.argv


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False").strip().lower() in (
    "true",
    "1",
    "yes",
    "y",
)

# 배포(DEBUG=False)에서는 DJANGO_SECRET_KEY가 반드시 있어야 한다.
# 로컬 개발/테스트에서만 고정 폴백을 허용한다.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or (
    "django-insecure-5l()ew9)0in=29ppj$m^uge_+eppw8mtzgkkhb0!g%fkki12ju"
    if DEBUG or IS_TEST_RUN
    else None
)
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY 환경변수가 설정되어야 합니다 (DEBUG=False인 배포 환경)."
    )

# DEBUG/테스트가 아닌 실제 배포 환경 여부. 프록시 뒤 HTTPS 강제 등 배포 전용 설정에 사용한다.
IS_PRODUCTION = not DEBUG and not IS_TEST_RUN

# 로컬 Mock/테스트는 별도 설정 없이 실행하되, 실제 배포에서는 반드시 환경변수로 교체한다.
APP_ENCRYPTION_KEY = (
    os.environ.get("APP_ENCRYPTION_KEY")
    or os.environ.get("PAYROLL_ENCRYPTION_KEY")  # 이전 배포 환경변수 호환
#   or ("ySLIQ7x5nymu0hMIhs4FDupeWcxDLIK4pd_yQm7RA9o=" if DEBUG else None)
    or (Fernet.generate_key().decode() if "test" in sys.argv else None)
)
# 외부 브랜치나 기존 코드가 참조할 수 있어 한동안 호환 alias를 유지한다.
PAYROLL_ENCRYPTION_KEY = APP_ENCRYPTION_KEY

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS",
        "localhost,127.0.0.1,testserver",
    ).split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    'corsheaders',
    'core',
    'payroll',
    'businesses',
    'analytics',
    'transactions',
    'settings',
    'reports',
    'tax',
    'chat',
    'benchmark',
]

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "").strip()
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-5.6-luna").strip()
OPENAI_TIMEOUT_SECONDS = float(os.environ.get("OPENAI_TIMEOUT_SECONDS", "20"))
OPENAI_MAX_OUTPUT_TOKENS = int(os.environ.get("OPENAI_MAX_OUTPUT_TOKENS", "1200"))
OPENAI_REASONING_EFFORT = os.environ.get("OPENAI_REASONING_EFFORT", "none").strip()

# 로컬/운영은 키가 있으면 OpenAI를 사용하고, 테스트는 실제 유료 호출을 차단한다.
_default_chat_responder = (
    "chat.services.openai_responder.OpenAIChatResponder"
    if OPENAI_API_KEY and "test" not in sys.argv
    else "chat.services.responder.RuleBasedChatResponder"
)
CHAT_RESPONDER_CLASS = (
    os.environ.get("CHAT_RESPONDER_CLASS", "").strip()
    or _default_chat_responder
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CODEF_MODE = "mock"
CODEF_MODE = os.environ.get("CODEF_MODE", "mock").strip().lower()

CODEF_CLIENT_ID = os.environ.get("CODEF_CLIENT_ID", "").strip()
CODEF_CLIENT_SECRET = os.environ.get("CODEF_CLIENT_SECRET", "").strip()
CODEF_API_BASE_URL = os.environ.get("CODEF_API_BASE_URL", "").strip().rstrip("/")
CODEF_TIMEOUT_SECONDS = float(
    os.environ.get("CODEF_TIMEOUT_SECONDS", "20")
)
CODEF_PUBLIC_KEY = os.environ.get("CODEF_PUBLIC_KEY", "").strip()

# 서울시 열린데이터광장(공공데이터 포털) 상권분석 OpenAPI 일반 인증키. 반드시 .env로만 주입한다.
SEOUL_DATA_API_KEY = os.environ.get("SEOUL_DATA_API_KEY", "").strip()
SEOUL_DATA_API_BASE_URL = os.environ.get("SEOUL_DATA_API_BASE_URL", "http://openapi.seoul.go.kr:8088").strip().rstrip("/")
SEOUL_DATA_TIMEOUT_SECONDS = float(os.environ.get("SEOUL_DATA_TIMEOUT_SECONDS", "10"))

PAYMENT_GATEWAY_MODE = "mock"

# ---------------------------------------------------------------------------
# 인증 / 인가 정책
# ---------------------------------------------------------------------------
# 데모 시연 모드. Authorization 헤더가 없는 요청을 데모 계정으로 인증하며,
# 그렇게 인증된 요청은 is_demo=True 사업장에만 접근할 수 있다(core.permissions).
# 실서비스 전환 시 .env에 DEMO_MODE=0 을 설정한다.
DEMO_MODE = os.environ.get("DEMO_MODE", "True").strip().lower() in (
    "true",
    "1",
    "yes",
    "y",
)
DEMO_USERNAME = os.environ.get("DEMO_USERNAME", "demo").strip()

# 소유자(owner)가 지정되지 않은 사업장에 대한 접근 허용 여부.
# 레거시 테스트 픽스처 호환용이며, 배포 런타임에서는 반드시 False여야 한다.
ALLOW_UNOWNED_BUSINESS_ACCESS = "test" in sys.argv

TEST_RUNNER = "core.test_runner.LegacyAuthTestRunner"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        # DEMO_MODE=True일 때만 동작한다. 순서상 반드시 Token 뒤에 온다.
        "core.authentication.DemoGuestAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
    "DEFAULT_THROTTLE_RATES": {
        # 로그인 무차별 시도 방어
        "login": "10/min",
        # 유료 LLM 호출 남용 방어 (데모 모드에서는 무인증 호출이 가능하므로 필수)
        "llm": "20/min",
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "카페비서 (Caffeine) API",
    "DESCRIPTION": "개인 카페/소상공인 세무·회계·노무·경영진단 AI 어시스턴트 API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
}

CORS_ALLOW_ALL_ORIGINS = os.environ.get("CORS_ALLOW_ALL_ORIGINS", "False").strip().lower() in (
    "true",
    "1",
    "yes",
    "y",
)
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://localhost:8080",
    ).split(",")
    if origin.strip()
]
CORS_URLS_REGEX = r"^/api/.*$"
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# ---------------------------------------------------------------------------
# 이메일 (세무사 리포트 발송)
# ---------------------------------------------------------------------------
# EMAIL_HOST_USER가 설정되면 실제 SMTP로 발송하고, 없으면 콘솔 백엔드로 대체한다.
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "").strip()
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "").strip()
EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
    if EMAIL_HOST_USER
    else "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com").strip()
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or "no-reply@caffeine.local"

# ---------------------------------------------------------------------------
# 배포 보안 헤더
# ---------------------------------------------------------------------------
# nginx가 X-Forwarded-Proto를 넘겨주므로, 이를 신뢰해 Django가 요청이 HTTPS인지
# 판단하게 한다. IS_PRODUCTION 가드는 테스트/로컬 dev(DEBUG=True)에서
# 리다이렉트나 secure 쿠키 때문에 요청이 막히지 않도록 하기 위함이다.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = IS_PRODUCTION
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION
SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO"),
    },
}
