# Generated by Django 5.2 on 2026-08-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', '4대보험 정직원'), ('PART_TIME', '단시간 근로자(주 15시간 미만)'), ('FREELANCER', '3.3% 프리랜서')], max_length=20)),
                ('hourly_wage', models.PositiveIntegerField()),
                ('monthly_contracted_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('rrn_front_encrypted', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
