# Generated by Django 5.2 on 2026-08-13 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('work_hours', models.DecimalField(decimal_places=1, max_digits=6)),
                ('gross_pay', models.PositiveIntegerField()),
                ('withholding_tax', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payroll.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'year', 'month'), name='uniq_employee_payment_per_month')],
            },
        ),
    ]
