# Generated by Django 5.2 on 2026-08-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
