# Generated by Django 5.2 on 2026-08-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_employee_work_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_long_term_contract',
            field=models.BooleanField(default=False),
        ),
    ]
