# Generated by Django 5.2 on 2026-08-14 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_codefconnection'),
        ('payroll', '0004_employee_is_long_term_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='businesses.business'),
            preserve_default=False,
        ),
    ]
