# Generated by Django 5.2 on 2026-08-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_employee_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '재직'), ('INACTIVE', '퇴사')], default='ACTIVE', max_length=20),
        ),
    ]
